apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-microservice-user
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: java-microservice-user
  template:
    metadata:
      labels:
        app: java-microservice-user
    spec:
      containers:
      - name: java-microservice-user
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 8080
